### ISSUE TITLE
Values not showing up in the rows with 'mirror-visibility' attribute enabled.

### ISSUE THREAD

**Issue by przemo** [susom/redcap-em-shazam#10]
It happens in the case when survey participant decides to save the results and generate an individual link which allows for returning to the survey at some other point in time. When you want to return to the survey, the fields with attribute 'mirror-visibility' are empty - values remain stored in the database, however.

**Comment by biggeeves** [comment]
I tried several variations of entered data with skip patterns and 'mirror-visibility'.  When returned to the survey the values were visible and correct.  They are present both in the database and the survey.  
REDCap Version = 8.6.1
External Module Version = 1.8

@przemo could you update and test again?  Post the results and this issue might be closed.

**Comment by 123andy** [comment]
@przemo - can you please give an update if this is still an issue?  If so, can you provide me with a survey url and return code for your server so I can see what's going on in javascript?

**Comment by przemo** [comment]
Hi, 
sorry for the delay. I will try to reproduce it next week. I did not have access to the survey for some time.

**Comment by 123andy** [comment]
I'm going to close this for now.  Let me know if you can reproduce and supply the dictionary.  Thx.

**Comment by przemo** [comment]
Indeed, with newer version of RedCap I could not reproduce the error. Thank you for looking into this.
