### ISSUE TITLE
Concern about duplicate locations for the same content

### ISSUE THREAD

**Issue by biggeeves** [susom/redcap-em-shazam#12]
There are two locations were Shazam HTML can be created and edited.  One location is in the Online Designer and the other is via ehe Shazam Setup link "prefix=shazam&page=config".

Having two locations store the "same" content is problematic.  Over time the content in each location can change leading to difficulties updating and debugging.  

**Example:** Updating the field in the Online Designer does not updated the HTML in the Shazam Configuration.  

_Suggested Improvements:_

**1)** The logical place to store the HTML is in the Online Designer.  When the Shazam Setup is used the HTML should retrieve the most recent HTML from the Online Designer.  This may mean overwriting/updating the original "Shazam" HTML.  To be fancy a check could be performed to see if they are different and display a pop up "The HTML is different: Options/Button 1) Keep Shazam HTML 2) Keep Online Designer HTML 3) Cancel / I'll look into it and decide later (which then disables the Save).  

**2)** Change the gold standard location to the Shazam HTML config.  Disable the Online Designer "Field Label" and insert placeholder text "The Field Label is edited by clicking on "Shazam Setup".

**Comment by 123andy** [comment]
Hi @biggeeves -  

Good points -- I pushed to move over a plugin so Sean Banks could use it for a project and never really thought through the design but I see what you're saying...  I'll look into it on the next iteration...
-A

**Comment by biggeeves** [comment]
Separating the presentation layer, "Shazam HTML", and the data dictionary is a good idea.  My preference is to lock the online designer field label.  Issues with that strategy include copying projects and making bulk edits/updates.

**Comment by 123andy** [comment]
This will have to be tackled on the next iteration.  I agree - it should be stored in the metadata.

**Comment by biggeeves** [comment]
Sounds good. Thanks!

**Comment by 123andy** [comment]
Closing as I don't think I'll ever get around to this.
