### ISSUE TITLE
Update shazam-mirror-visibility to data-shazam-mirror-visibility

### ISSUE THREAD

**Issue by biggeeves** [susom/redcap-em-shazam#13]
In PHP Storm shazam-mirror-visibility is highlighted warning is "attribute shazam-mirror-visibility is not allowed here".  Adding the prefix "**data-**" would remove the error.  

Old: shazam-mirror-visibility 
New: **data-**shazam-mirror-visibility

HTML5 is designed with extensibility in mind for data that should be associated with a particular element but need not have any defined meaning. data-* attributes allow us to store extra information on standard, semantic HTML elements without other hacks such as non-standard attributes, extra properties on DOM, or Node.setUserData().

**Comment by 123andy** [comment]
This was done as part of the 1.3.0 release.  All existing shazam-mirror-visibility settings will be automatically migrated to data-shazam-mirror-visibility on the next load/save.
