### ISSUE TITLE
Failure during Upgrade to 1.2.1

### ISSUE THREAD

**Issue by biggeeves** [susom/redcap-em-shazam#16]
During the REDCap "update" process I got the following error (copied from Chrome Developer Tools, 

AJAX Request Error: An error occurred while enabling the module: <div class='red' style='max-width:700px;'>
							<b>ERROR:</b> There is an error in the REDCap plugin that you are currently using. Please contact
	this plugin's developer and send them the error info listed below so that they may fix this issue.
	If you do not know who the developer is for this plugin, then notify your REDCap administrator about this issue.<br><br>
							<b>Error message:</b> Uncaught Error: Call to undefined function ExternalModules\isCompatibleFormatCorrect() in D:\redcap\redcap_v8.6.1\ExternalModules\classes\ExternalModules.php:1478
Stack trace:
#0 D:\redcap\redcap_v8.6.1\ExternalModules\classes\ExternalModules.php(517): ExternalModules\ExternalModules::isCompatibleWithREDCapPHP('shazam', 'v1.2.1')
#1 D:\redcap\redcap_v8.6.1\ExternalModules\classes\ExternalModules.php(562): ExternalModules\ExternalModules::enableForProject('shazam', 'v1.2.1', NULL)
#2 D:\redcap\redcap_v8.6.1\ExternalModules\classes\ExternalModules.php(568): ExternalModules\ExternalModules::enable('shazam', 'v1.2.1')
#3 D:\redcap\redcap_v8.6.1\ExternalModules\manager\ajax\enable-module.php(44): ExternalModules\ExternalModules::enableAndCatchExceptions('shazam', 'v1.2.1')
#4 {main}
  thrown <br>
							<b>File:</b> D:\redcap\redcap_v8.6.1\ExternalModules\classes\ExternalModules.php <br>
							<b>Line:</b> 1478
						</div>

Screen shot is below:

![image](https://user-images.githubusercontent.com/3834165/45106490-aa8d7300-b0eb-11e8-92ac-5aa772532644.png)

**Comment by 123andy** [comment]
Hey @biggeeves  -  Any thoughts on this?  Is it still an issue?

**Comment by 123andy** [comment]
Going to close for now and hope this was an aberration.  Let me know if otherwise.  Thx - Andy
