### ISSUE TITLE
Using same fields in different shazam via branching logic

### ISSUE THREAD

**Issue by lukerowsell** [susom/redcap-em-shazam#17]
Not sure if this is outside of possibilities but I wanted to change a shazam table based on an external field

ie. Redcap field: No of people = 1 / 2 / 3 / 4
....branches to shazam field 1 / 2 / 3 / 4
which call either 1, 2, 3 or 4 row table (but call common fields)

        Patient 
1      Jeff        
2      Bob
3      Alex
4      Matt

or 

        Patient 
1      patient1
2      patient2
3      patient3

The shazam fields only work in the first version of the table that is selected.  In other selections, the table shows but only display the variable name, rather than the contents, as above.  This remains constant throughout the database

**Comment by 123andy** [comment]
Hi Luke, 
When you 'shazam' a field into a table, you are physically moving that input into the table.  You cannot have the same input in two tables on the same form.  It just doesn't work that way.  Hope that makes sense - I'm not 100% sure I am following your question correctly.
