### ISSUE TITLE
Shazam not playing nicely with matrices in surveys. 

### ISSUE THREAD

**Issue by denshade** [susom/redcap-em-shazam#18]
Using shazaam in a survey in combination with a matrix scrambles the layout of the matrix. 

I've identified that the problem has to do with this line of code: 

   $('td.questionnum').parent().not('.shazam-vanished').find('td.questionnum').each(function(){
        if($(this).text() !== "") {
            Shazam.log("this is not empty",this);
            allEmpty = false;
        }
    });
    if (allEmpty) {
        Shazam.log("all td.questionnum are empty");

Culprit ->>   //$('td.questionnum').hide(); //css({"position":"absolute","width":"0px !important","height": "0px !important","opacity":"0"});
    }
}
Below are two screenshots with and without the $('td.questionnum').hide(); enabled. 

![2018-11-08 09_09_18-my first instrument](https://user-images.githubusercontent.com/1488061/48185700-27c8a480-e336-11e8-958d-43128b3cfd1f.png)

![2018-11-08 09_09_38-my first instrument](https://user-images.githubusercontent.com/1488061/48185701-27c8a480-e336-11e8-953e-356e60390a2d.png)

**Comment by 123andy** [comment]
@navah93 @denshade  - I've fixed this I think by filtering out matrix td.labels from the hide:
```javascript
$('tr:not("[mtxgrp]") td.questionnum').hide();
```
I'll try to push out later today or tomorrow.

**Comment by navah93** [comment]
> @navah93 @denshade - I've fixed this I think by filtering out matrix td.labels from the hide:
> 
> ```js
> $('tr:not("[mtxgrp]") td.questionnum').hide();
> ```
> 
> I'll try to push out later today or tomorrow.

Thank you for responding. But my problem is that shazam.js not uploaded at all. What may cause it? 
Thank you,
Navah

**Comment by 123andy** [comment]
I haven’t pushed the update to REDCap yet - trying to get a few more fixes in.  You can manually adjust your existing Shazam.js file (near the end) until then…

-A

On Nov 26, 2018, at 11:19 PM, navah93 <notifications@github.com<mailto:notifications@github.com>> wrote:


@navah93<https://github.com/navah93> @denshade<https://github.com/denshade> - I've fixed this I think by filtering out matrix td.labels from the hide:

$('tr:not("[mtxgrp]") td.questionnum').hide();

I'll try to push out later today or tomorrow.

Thank you for responding. But my problem is that shazam.js not uploaded at all. What may cause it?
Thank you,
Navah
