### ISSUE TITLE
greenhighlight wrapped around html

### ISSUE THREAD

**Issue by biggeeves** [susom/redcap-em-shazam#20]
REDCap version: 8.10.2
Shazam Version: 1.3.3
Browser Chrome: Latest Version.

There is a greenhighlight class inserted somehow.  

This is the code for the shazam table block:  <tr id="spe_shazam_table-tr" sq_id="spe_shazam_table"><td class="labelrc col-12 greenhighlight" colspan="2">

It causes the background color in the table below to turn green.  It's hard to read. 

The css is: 

.greenhighlight {
    background-color: #DBF7DF !important;
}

The temporary workaround is to wrap the custom HTML in a div.  Then the more specific custom css: 
.greenhighlight div, .greenhighlight  div table td { 
    background-color: #f5f5f5 !important; 
}
.greenhighlight div {
    margin: -2px -5px;
}

which removes the green background color.

Below is a javascript error:

Uncaught TypeError: Cannot read property 'spe_shazam_table-tr' of undefined
    at index.php?pid=XX&id=XXX&event_id=XXX&page=biospecimen_collection:1073
   
`<tr id="spe_shazam_table-tr" sq_id="spe_shazam_table"><td class="labelrc col-12 greenhighlight" colspan="2">
<div class="clear-background">
<h2 class="text-center">Biospecimen Collection</h2>
<table class="biospecimen table">
    <tbody><tr>
        <td><span class="tilt">Lab Location</span></td>
        <td><span class="tilt">Number &amp; Type<br> of Tubes</span></td>
        <td><span class="tilt">Colletion<br>Date</span></td>
        <td><span class="tilt">Collection<br>Time</span></td>
        <td><span class="tilt">Drawn by</span></td>
        <td><span class="tilt">Confirmed Delivered</span></td>
    </tr>
    <tr>
        <td class="lavender-tube">Cremer's Lab<br> (PH10)<br>Lavender Tube</td>
        <td>
            <div class="shazam"><input autocomplete="new-password" aria-labelledby="label-lav_tube note-lav_tube" class="x-form-text x-form-field " type="text" name="lav_tube" value="" onblur="redcap_validate(this,'0','1','soft_typed','integer',1)" tabindex="0" fv="integer" style="font-weight: normal; background-color: rgb(255, 255, 255);"><div id="note-lav_tube" class="note" aria-hidden="true">(0-1)</div></div>
        </td>
        <td>
            <div class="shazam"><input autocomplete="new-password" aria-labelledby="label-lav_coll_dt" class="x-form-text x-form-field date_mdy hasDatepicker" type="text" name="lav_coll_dt" value="" onblur="redcap_validate(this,'2010-01-01','2035-01-01','soft_typed','date_mdy',1)" tabindex="0" onkeydown="dateKeyDown(event,'lav_coll_dt')" fv="date_mdy" id="dp1548436903475"><img class="ui-datepicker-trigger" src="/redcap_v8.10.2/Resources/images/date.png" alt="Click to select a date" title="Click to select a date"><span class="df">M-D-Y</span></div>
        </td>
        <td>
            <div class="shazam"><input autocomplete="new-password" aria-labelledby="label-lav_coll_time" class="x-form-text x-form-field time2 hasDatepicker" type="text" name="lav_coll_time" value="" onblur="redcap_validate(this,'','','soft_typed','time',1)" tabindex="0" fv="time" id="dp1548436903480"><img class="ui-datepicker-trigger" src="/redcap_v8.10.2/Resources/images/timer.png" alt="Click to select a time" title="Click to select a time"><span class="df">H:M</span></div>
        </td>
        <td>
            <div class="shazam"><input autocomplete="new-password" aria-labelledby="label-lav_by note-lav_by" class="x-form-text x-form-field " type="text" name="lav_by" value="" onblur="redcap_validate(this,'','','soft_typed','alpha_only',1)" tabindex="0" fv="alpha_only"><div id="note-lav_by" class="note" aria-hidden="true">initials</div></div>
        </td>
        <td>
            <div class="shazam"><input name="lav_delivered" value="" tabindex="-1" class="hiddenradio" aria-labelledby="label-lav_delivered"><span class="choicehoriz" onclick="sr(this,event)"><input type="radio" tabindex="0" name="lav_delivered___radio" aria-labelledby="label-lav_delivered label-lav_delivered-1" onclick="document.forms['form'].lav_delivered.value=this.value;" value="1"> <label id="label-lav_delivered-1" class="mc">Yes</label></span><span class="choicehoriz" onclick="sr(this,event)"><input type="radio" tabindex="0" name="lav_delivered___radio" aria-labelledby="label-lav_delivered label-lav_delivered-0" onclick="document.forms['form'].lav_delivered.value=this.value;" value="0"> <label id="label-lav_delivered-0" class="mc">No</label></span><div class="resetLinkParent" style="text-align: left;"><a href="javascript:;" class="smalllink " tabindex="0" style="display:;" onclick="return radioResetVal('lav_delivered','form');">reset</a></div></div>
        </td>
    </tr>
    <tr>
</tr></tbody></table>
</div></td></tr>`

**Comment by biggeeves** [comment]
The green highlight is caused by the Shazam field receiving focus and REDCap changing the field of focus to green.  Since many fields and other elements to are embedded within a single Shazam field, the background for everything turns green.  In essence, this is not a bug, it is a feature.

The expected behavior is for the current field, embedded in Shazam or not, to turn green while all other fields have the dull grey background.  

Suggestion: Use JavaScript to remove the class "greenhighlight" from the Shazam field and place it on the current field of focus.  

**Ultimately it is developers choice**: close the issue or drill down.  Both are correct and acceptable.

**Comment by 123andy** [comment]
I've added css to just disable that green highlight when using shazam in the past... It is kind of annoying because it is done dynamically with javascript on REDCaps part.  Another alternative would be to find that function and disable it (override it).  Haven't gotten there.  Open to a pull request :-)

-A
