### ISSUE TITLE
Table not displaying, would appreciate some help

### ISSUE THREAD

**Issue by omarrayward** [susom/redcap-em-shazam#21]
Hi @123andy I was not able to display the table within the field.

I've set up a pretty simple html:
```html
<!-- Add your Shazam HTML Here -->
<table class='whatever'>
    <tr>
        <th></th>
        <th>2012</th>
    </tr>
    <tr>
        <th>Fentanyl dosis</th>
        <td>
            <div class='shazam'>var_1</div>
        </td>
    </tr>
</table>
```

And I have 2 fields:
`fentanyl_1` as a "descriptive" field which is meant to be the container field that will be holding the other fields. 
`var_1` is the field to be displayed as a "text" field. 

When I inspect the html file rendered I see this snippet of js:
```javascript
...
{
    Shazam.fields = ["fentanyl_1"];
    Shazam.isDev = 0;
    $(document).ready(function () {
        Shazam.highlightFields();
    });
}            
```

But somehow I don't see any code calling `Shazam.Transform()` which by reading the code should be modifying the container to include the html table defined. 

Any clue on what I be missing?

Thanks for your help.

**Comment by 123andy** [comment]
If you open your 'developer tools' on your browser (I use chrome or firefox).  Then goto the 'Network Tab' - you should see that when you load the page with Shazam on it, there should be a shazam.js file that is also loaded.  Are you seeing this?  Are there any red warnings about js issues?

**Comment by omarrayward** [comment]
@123andy We were able to figure out. Closing now
