### ISSUE TITLE
Problem while installing Shazam external module in REDCap. Error message given below

### ISSUE THREAD

**Issue by skbiostat** [susom/redcap-em-shazam#22]
REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught exception 'Exception' with message 'You must specify a module to delete!' in C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\classes\ExternalModules.php:2598 Stack trace: #0 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\classes\ExternalModules.php(2533): ExternalModules\ExternalModules::deleteModuleDirectory(false, true) #1 C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\manager\ajax\download-module.php(4): ExternalModules\ExternalModules::downloadModule('279', false, true) #2 {main} thrown
File: C:\Program Files\Apache Software Foundation\Apache2.2\htdocs\redcap\redcap_v8.7.2\ExternalModules\classes\ExternalModules.php
Line: 2598

**Comment by 123andy** [comment]
I think this is an issue with the External Modules code - and not Shazam.  I'm going to move this over to that github:  
https://github.com/vanderbilt/redcap-external-modules/issues/175
