### ISSUE TITLE
shazam branching error - risk of orphan data

### ISSUE THREAD

**Issue by sannethomsen** [susom/redcap-em-shazam#23]
Without shazam I cannot change type from drug to procedure if there is data in the drug field witout redcap "complaining" that there is data in field no longer visible. But using shazam I do not get any error message changing the type, when there is data in e.g. drug field. So the risk of orphan data is greater using shazam.

**Comment by 123andy** [comment]
Sorry @sannethomsen  - not sure what to do here.  Shazam may not be the option for you.
