### ISSUE TITLE
Save shazam configuration to backup file

### ISSUE THREAD

**Issue by gevro** [susom/redcap-em-shazam#31]
Hi, Is there a way to do this? The standard REDCap backup xml doesn't seem to contain all the shazam code I configured.

**Comment by 123andy** [comment]
It is on my dev queue... It currently backs up recent configs in a json object that is written to the external-module-settings table.  I haven't yet made an option to download/upload the settings but agree that would be useful.

**Comment by 123andy** [comment]
You would have to use a db tool to pull the backup from the external module settings.
