### ISSUE TITLE
Add an example project?

### ISSUE THREAD

**Issue by pbchase** [susom/redcap-em-shazam#33]
@123andy, what do you think about adding an example project to the module? We've been doing this more of our modules of late. It provides a useful demo project for end users and a good testing tool for developers. 

The motivation that pushed us over the edge was code review work within my shop. I found the code authors were routinely passing test projects to the reviewer via the conversation in the pull requests instead of adding the test projects in a commit. Anything that valuable is worth adding to the source code. What's more, if we ever add automated testing to our module repos, the tools we use for manual testing will provide a good foundation.

I thought the RECap community post [Shazam Sample Project](https://community.projectredcap.org/content/idea/78670/shazam-sample-project.html) might provide good fodder. I bet you have one of these laying around as well.

**Comment by pbchase** [comment]
FYI, we could make the PR. I just though I'd solicit interest before putting in the time.

**Comment by 123andy** [comment]
Sure - sounds great.  We could just cheat and put a link to Scott's survey :-).  
https://mrprcbcw.hosts.jhmi.edu/redcap/surveys/?s=HJ8H7YTKDA

**Comment by 123andy** [comment]
I just added a little to the readme.  Ideally you should be able to copy/paste the configuration into the UI, but I haven't had motivation to do much...
