### ISSUE TITLE
Matrix input missing in data export

### ISSUE THREAD

**Issue by mojogolaso** [susom/redcap-em-shazam#38]
@susom I have modified the HTML code example on the main Github page only slightly (using the mirror-visibility function for each row to work as branching logic), but I find that when I try to export data from a finished survey, the export completely ignores any input to the Shazam module. I've included my HTML code at the bottom of this post, which works beautifully in the actual survey. Here is a screen shot of the survey, with all rows shown, answered with "5":
![Screen Shot 2020-07-09 at 12 55 43 PM](https://user-images.githubusercontent.com/36083965/87074340-b5842380-c1ec-11ea-8aef-3ec9d214f151.png)

When I try to view the finished survey record itself within RedCap, it shows the rows which were answered, but all the inputs are blank:
![Screen Shot 2020-07-09 at 12 56 26 PM](https://user-images.githubusercontent.com/36083965/87074356-ba48d780-c1ec-11ea-9c81-5df33607c6ef.png)

In a data export, the Shazam fields are not even included. Is this a known limitation of the Shazam module? Or is there something in my HTML code which is preventing data export from detecting the Shazam module?

Here is the HTML code:
<table class='fy_summary'
       border="1">
    <tr>
        <th></th>
        <th>1-5 min duration</th>
        <th>6-20 min duration</th>
        <th>20+ min duration</th>
    </tr>
    <tr>
        <tr data-shazam-mirror-visibility="contacts_t_25">
        
        <th># of interactions w/ Patients that last for:</th>
        <td>
            <div class='shazam shazam-icons'><input type="number" name="#Pmin_t" id="#Pmin_t" min="0" max="100"/></div>
        </td>
        
        <td>
            <div class='shazam'><input type="number" name="#Pmed_t" id="#Pmed_t" min="0" max="100" /></div>
        </td>
        <td>
            <div class='shazam'><input type="number" name="#Pmax_t" id="#Pmax_t" min="0" max="100" /></div>
        </td>
     
    </tr>
    <tr>
        <tr data-shazam-mirror-visibility="contacts_t_26">
       
        <th># of interactions w/ "Physician, NP, PA, etc"  that last for:</th>
       <td>
            <div class='shazam shazam-icons'><input type="number" name="#Dmin_t" id="#Dmin_t" min="0" max="100"/></div>
        </td>
        
      
        <td>
            <div class='shazam'><input type="number" name="#Dmed_t" id="#Dmed_t" min="0" max="100" /></div>
        </td>
        <td>
            <div class='shazam'><input type="number" name="#Dmax_t" id="#Dmax_t" min="0" max="100" /></div>
        </td>

    </tr>
    <tr>
        <tr data-shazam-mirror-visibility="contacts_t_27">

        <th> # of interactions w/ "Nurse, nurse aid, LPN, etc" that last for:</th>
       <td>
            <div class='shazam shazam-icons'><input type="number" name="#Nmin_t" id="#Nmin_t" min="0" max="100"/></div>
        </td>
        
        <td>
            <div class='shazam'><input type="number" name="#Nmed_t" id="#Nmed_t" min="0" max="100" /></div>
        </td>
        <td>
            <div class='shazam'><input type="number" name="#Nmax_t" id="#Nmax_t" min="0" max="100" /></div>
        </td>
     
    </tr>
        <tr data-shazam-mirror-visibility="contacts_t_28">
        
        <th># of interactions with "Admin/Support staff" that last for:</th>
        <td>
            <div class='shazam shazam-icons'><input type="number" name="#Amin_t" id="#Amin_t" min="0" max="100"/></div>
        </td>
        
        <td>
            <div class='shazam'><input type="number" name="#Amed_t" id="#Amed_t" min="0" max="100" /></div>
        </td>
        <td>
            <div class='shazam'><input type="number" name="#Amax_t" id="#Amax_t" min="0" max="100" /></div>
        </td>
     
    </tr>
        <tr data-shazam-mirror-visibility="contacts_t_29">
        
        <th># of interactions with "Students" that last for:</th>
        <td>
            <div class='shazam shazam-icons'><input type="number" name="#Smin_t" id="#Smin_t" min="0" max="100"/></div>
        </td>
        
        <td>
            <div class='shazam'><input type="number" name="#Smed_t" id="#Smed_t" min="0" max="100" /></div>
        </td>
        <td>
            <div class='shazam'><input type="number" name="#Smax_t" id="#Smax_t" min="0" max="100" /></div>
        </td>
  
    </tr>
        <tr data-shazam-mirror-visibility="contacts_t_30">
        
        <th># of interactions with "Other Co-worker types" that last for:</th>
        <td>
            <div class='shazam shazam-icons'><input type="number" name="#Omin_t" id="#Omin_t" min="0" max="100"/></div>
        </td>
        
        <td>
            <div class='shazam'><input type="number" name="#Omed_t" id="#Omed_t" min="0" max="100" /></div>
        </td>
        <td>
            <div class='shazam'><input type="number" name="#Omax_t" id="#Omax_t" min="0" max="100" /></div>
        </td>
   
    </tr>
</table>

**Comment by 123andy** [comment]
I'm afraid this looks odd.  Is the HTML you've shown the html of the Shazam configuration tab?  If so, you should not be including any <input> html tags.  You should only be including the name of the redcap field.  Shazam then builds the actual html by moving the redcap field into the shazam html skeleton.

For example:
 In the shazam editor, the html tab should look like:

```html
<tr data-shazam-mirror-visibility="contacts_t_30">
    <!-- This will make this entire row only visible when the field "Other" on pg 2 of survey is visible -->
    <!-- including shazam-icons will add the history / data quality icons -->
    <th># of interactions with "Other Co-worker types" that last for:</th>
    <td>
        <div class='shazam shazam-icons'>Omin_t</div>
    </td>
    <td>
        <div class='shazam'>Omed_t</div>
    </td>
    <td>
        <div class='shazam'>Omax_t</div>
    </td>
</tr>
```

**Comment by 123andy** [comment]
This assumes that you have fields "0min_t", "0max_t", etc... on the same page as the shazam descriptive field.

**Comment by mojogolaso** [comment]
That was the problem, and it fixed the issue. THANK YOU! I didn't know that including other HTML tags within the Shazam HTML (instead of doing as a RedCap field) was a no-no. Now it exports through RedCap.
