### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by cecape** [susom/redcap-em-shazam#39]
Hey, 

When trying to download shazam on REDCap I encounter the following error (I am new to github and REDCap so I am sorry if this would be an easily resolvable issue but I don't know what is going wrong): 

REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught Exception: The request to retrieve the name for module 744 from the repo failed: . in /var/www/html/redcap_v10.0.2/ExternalModules/classes/ExternalModules.php:4199 Stack trace: #0 /var/www/html/redcap_v10.0.2/ExternalModules/manager/ajax/download-module.php(6): ExternalModules\ExternalModules::downloadModule(744, false, true) #1 {main} thrown
File: /var/www/html/redcap_v10.0.2/ExternalModules/classes/ExternalModules.php
Line: 4199

**Comment by 123andy** [comment]
I take it you were able to figure this out? @cecape

**Comment by cecape** [comment]
Yes. It was a problem created by the people who run our REDCap servers. I am not sure what it is they did exactly but they managed to fix it. Thanks for asking.
