### ISSUE TITLE
Undefined constant SUPER_USER 

### ISSUE THREAD

**Issue by dcarmi-uob** [susom/redcap-em-shazam#44]
Using PHP8 we are seeing then following error message coming in by email. It can be activated by a survey respondent filling in a survey. It is not apparent using earlier version of PHP.

[This message was automatically generated by REDCap]

Error: Undefined constant "Stanford\Shazam\SUPER_USER" in /var/www/html/clindev/redcap/modules/shazam_v1.3.9/Shazam.php:322
Stack trace:
#0 /var/www/html/clindev/redcap/redcap_v10.6.21/ExternalModules/manager/templates/hooks/every_page_top.php(41): Stanford\Shazam\Shazam->redcap_module_link_check_display('48', Array)
#1 /var/www/html/clindev/redcap/redcap_v10.6.21/ExternalModules/classes/ExternalModules.php(3041): require('/var/www/html/c...')
#2 /var/www/html/clindev/redcap/redcap_v10.6.21/ExternalModules/classes/ExternalModules.php(2889): ExternalModules\ExternalModules::safeRequire('/var/www/html/c...', Array)
#3 /var/www/html/clindev/redcap/redcap_v10.6.21/Classes/Hooks.php(42): ExternalModules\ExternalModules::callHook('every_page_top', Array)
#4 /var/www/html/clindev/redcap/redcap_v10.6.21/Classes/HtmlPage.php(126): Hooks::call('redcap_every_pa...', Array)
#5 /var/www/html/clindev/redcap/redcap_v10.6.21/Surveys/index.php(1996): HtmlPage->PrintHeader()
#6 /var/www/html/clindev/redcap/surveys/index.php(9): include('/var/www/html/c...')
#7 {main}

**Comment by 123andy** [comment]
This has been patched in release 1.3.10
