### ISSUE TITLE
Unexpected fatal error on PHP8 with non-superusers

### ISSUE THREAD

**Issue by tertek** [susom/redcap-em-shazam#48]
When trying to save new input in the "Shazam Editor", the request with action=save to "/ExternalModules/?prefix=shazam&page=config&pid=81" returns 200 but fails with following error:

```
REDCap crashed due to an unexpected fatal PHP error!

Error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in modules/shazam_v1.3.10/config.php:247 Stack trace: #0 modules/shazam_v1.3.10/config.php(247): in_array() #1 redcap_v12.4.21/ExternalModules/index.php(126): require('...') #2 {main} thrown
File: modules/shazam_v1.3.10/config.php
Line: 247
```

This error does *not* occur when testing with superusers.
Could be fixed with PHP8 array casting.

**Comment by 123andy** [comment]
Releasing a patch tonight.  Thanks!

**Comment by tertek** [comment]
@123andy thank you!

**Comment by 123andy** [comment]
I had to submit a second time to address some Psalm issues but resubmitted again.

-a
________________________________

**Comment by tertek** [comment]
Okay thx
