### ISSUE TITLE
Source content rows come back onto the screen with long field labels

### ISSUE THREAD

**Issue by dr01d3r** [susom/redcap-em-shazam#5]
Something about this style choice is allowing content to bleed back onto the screen when field labels are more than a couple words (i.e. 1 or more sentences).

https://github.com/susom/redcap-em-shazam/blob/5655240f4cf4a9edfc4da9eea0f8215a08d5c30e/js/shazam.js#L182

![shazam_field_display_issue](https://user-images.githubusercontent.com/2850680/36276693-589b7244-1254-11e8-853a-35f55b23cf68.PNG)

Basic testing seems to show that if I remove the text content within the original field label TD, it no longer renders on screen.  I see that you commented out the choice to hide them.  Is there any reason that we cannot use that approach instead?

**Comment by 123andy** [comment]
Hmm..  I'm wondering if it has to do with the shazam-mirror-visibility?  If that wasn't working.  Not really clear.  So, one option is to push it to the right a few thousand or to try the hiding.  I'm afraid I don't remember.  Please make a pull and I'll push it out...  I really haven't been using this directly for some time.  Thanks!

-Andy
—
Andrew Martin, PhD
Stanford University School of Medicine

On Feb 15, 2018, at 11:31 AM, Chris Kadolph <notifications@github.com<mailto:notifications@github.com>> wrote:


Something about this style choice is allowing content to bleed back onto the screen when field labels are more than a couple words (i.e. 1 or more sentences).

https://github.com/susom/redcap-em-shazam/blob/5655240f4cf4a9edfc4da9eea0f8215a08d5c30e/js/shazam.js#L182

[shazam_field_display_issue]<https://user-images.githubusercontent.com/2850680/36276693-589b7244-1254-11e8-853a-35f55b23cf68.PNG>

Basic testing seems to show that if I remove the text content within the original field label TD, it no longer renders on screen. I see that you commented out the choice to hide them. Is there any reason that we cannot use that approach instead?

**Comment by dr01d3r** [comment]
Branching logic and shazam-mirror-visibility was the reason you couldn't use hide().  Because once a condition is met, the original row displays again.  This will take a bit more consideration to see what might be a proper solution.  Perhaps, deleting the original rows as a final step?  If I have time this weekend, I'll fork it and try it out.

**Comment by dr01d3r** [comment]
To follow up on this, we've made due with a temporary fix that just increases the negative margin to -8000px.  It's getting the job done but I don't think it's worth a pull request given it's just a band-aid and not a solution.

**Comment by 123andy** [comment]
I've added your fix and a little more CSS @dr01d3r.  will release a new version today with some other bug fixes as well.
