### ISSUE TITLE
Data History & Field Comment Log/Data Resolution Workflow icons displayed twice

### ISSUE THREAD

**Issue by steentje34** [susom/redcap-em-shazam#7]
Hi @123andy,

When the option 'Display Data History & Field Comment Log/Data Resolution Workflow Icons' and field labels are used in the Shazam table, the icons are now displayed twice.
![image](https://user-images.githubusercontent.com/29727779/37703364-bcc513f4-2cf5-11e8-8513-48fc9aba2736.png)

I think this is linked to the line of code below.
https://github.com/susom/redcap-em-shazam/blob/26d75ccf9c3a49124f8ef6aff61c4f8aa4a2d8d4/js/shazam.js#L149

Maybe this could be solved by changing the code to the code below? I do not know if this could possibly break other features in the Shazam external module...
`var source_label = $("#label-" + search_field + " td:first);`

**Comment by 123andy** [comment]
Thanks @steentje34 !  I've added your fix and will release again today.
