### ISSUE TITLE
Generic "error" when user doesn't have rights

### ISSUE THREAD

**Issue by iznaut** [susom/redcap-em-shazam#8]
I enabled Shazam on a project and forgot to check the User Rights for the user. She was still able to see the Shazam Setup link in the sidebar and edit the associated code for a field. When attempting to save, however, a popup message would display "error" and no other information.

It seems like a user that doesn't have rights should not even be able to see the Shazam Setup link? Or at least the error message should be more verbose so the issue is clear.

**Comment by 123andy** [comment]
Valid points, @eaneuhaus.  I just implemented the fix.  It is available here if you want to download it manually:  https://github.com/susom/redcap-em-shazam/archive/v1.1.3.zip  or it should appear on the repo in a day or two.
